language: cpp

os:
 - linux
 - osx

compiler:
  - gcc
  - clang

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./dependencies/ci_linux.sh ; fi
  - if [ "$TRAVIS_OS_NAME" = "os" ]; then ./dependencies/ci_osx.sh ; fi

script: 
 - cmake .
 - make
 - make doc 
