language: cpp

compiler:
  - clang
  - gcc

before_install:
 - sudo apt-get update
 - sudo apt-get install libann-dev libboost-program-options-dev libboost-dev libtbb-dev libmetis-dev;
script: 
 - cmake .
 - make 
