language: cpp
sudo: required

os:
 - linux
 - osx

compiler:
  - gcc
  - clang

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then chmod 777 ./dependencies/ci_linux.sh ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then chmod 777 ./dependencies/ci_osx.sh ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./dependencies/ci_linux.sh ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./dependencies/ci_osx.sh ; fi

script: 
 - cmake .
 - make VERBOSE=1
 - make test
