language: cpp
sudo: required

os:
 - ubuntu
 - osx

compiler:
  - gcc
  - clang

before_install:
  - if [ "$TRAVIS_OS_NAME" = "ubuntu" ]; then chmod 777 ./travis/ci_ubuntu.sh ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then chmod 777 ./travis/ci_osx.sh ; fi
  - if [ "$TRAVIS_OS_NAME" = "ubuntu" ]; then ./travis/ci_ubuntu.sh ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./travis/ci_osx.sh ; fi

script: 
 - mkdir build
 - cd build
 - cmake ..
 - make VERBOSE=1
 - make test
