language: cpp
sudo: false

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libann-dev 
            - libboost1.55-all-dev 
            - libtbb-dev
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libann-dev 
            - libboost1.55-all-dev 
            - libtbb-dev
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - libann-dev 
            - libboost1.55-all-dev 
            - libtbb-dev
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - libann-dev 
            - libboost1.55-all-dev 
            - libtbb-dev
 
      env: COMPILER=clang++-3.7

#before_install:
#  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then chmod 777 ./travis/ci_osx.sh ; fi
#  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./travis/ci_osx.sh ; fi

script: 
 - mkdir build
 - cd build
 - cmake ..
 - make VERBOSE=1
 - make test
